<?php

namespace ML\TicketingBundle\Repository;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends \Doctrine\ORM\EntityRepository
{
    public function countTicketsByDay($date)
    {
        $qb = $this->createQueryBuilder('b');
        $qb //->select('count(b)')
            ->where('b.visitDay = :date')
            ->setParameter('date', $date)
        ;

        $qb ->leftJoin('b.tickets', 't')
            ->addSelect('t')
            ->select('count(t)')
        ;

        return $qb
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
