# src/ML/TicketingBundle/Resources/config/routing.yml

ml_ticketing_homepage:
    path: /
    defaults:
        _controller: MLTicketingBundle:Ticketing:index

ml_ticketing_schedule:
    path: /schedule
    defaults:
        _controller: MLTicketingBundle:Ticketing:schedule
