services:
    ml_ticketing.price:
        class: ML\TicketingBundle\ComputePrice\MLComputePrice
        arguments:
            - "@ml_ticketing.recover"

    ml_ticketing.recover:
        class: ML\TicketingBundle\ComputePrice\MLRecoverData

    ml_ticketing.stripe:
        class: ML\TicketingBundle\StripeService\MLStripeService

parameters:
    max: 1000