services:
    ml_ticketing.compute_price:
        class: ML\TicketingBundle\ComputePrice\MLComputePrice
        arguments:
            - "@ml_ticketing.recover_data"

    ml_ticketing.recover_data:
        class: ML\TicketingBundle\RecoverData\MLRecoverData

    ml_ticketing.stripe_service:
            class: ML\TicketingBundle\StripeService\MLStripeService
            arguments:
                - "@request_stack"

    ml_ticketing.bill_mailer:
        class: ML\TicketingBundle\Email\BillMailer
        arguments:
            - "@mailer"
            - "@twig"

    ml_ticketing.bill_listener:
        class: ML\TicketingBundle\DoctrineListener\BillListener
        arguments:
            - "@ml_ticketing.bill_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ml_ticketing.validator_unavailable_date:
        class: ML\TicketingBundle\Validator\UnavailableDateValidator
        arguments:
            - "@ml_ticketing.recover_data"
        tags:
            - { name:  validator.constraint_validator, alias: ml_ticketing_unavailable_date }

    ml_ticketing.validator_after_hour:
        class: ML\TicketingBundle\Validator\AfterHourValidator
        arguments:
            - "@request_stack"
            - "@ml_ticketing.recover_data"

        tags:
            - { name:  validator.constraint_validator, alias: ml_ticketing_after_hour }

## Service parameters for TicketingBundle only
parameters:
    ## Maximum accommodation capacity for the museum in number of pax
    ## Use with Bill entity method countTicketsByDay to compare
    maxCapacity: 1000